import { Button } from '@chakra-ui/button'
import { Box, Container, Text } from '@chakra-ui/layout'
import { useRouter } from 'next/dist/client/router'
import Head from 'next/head'
import IndexDemo from '../components/index-demo/index-demo.component'
import IndexHero from '../components/index-hero/index-hero.component'
import WhyUs from '../components/index-why-us/index-why-us.component'
import SectionHeader from '../components/section-header'

export default function Home() {
  const router = useRouter();
  return (
    <Box display="flex" flexDirection="column" position="relative" my="10px" w="100%">
      <Head>
        <title>PolyglotPal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box my="8">
        <Container maxW={{ base: "sm", md: "6xl" }}>
          <IndexHero />
        </Container>
      </Box>
      <Box bg="brand.200" my="8">
        <Container maxW={{ base: "sm", md: "6xl" }}>
          <IndexDemo />
        </Container>
      </Box>
      <Box my="8">
        <Container maxW={{ base: "sm", md: "6xl" }}>
          <WhyUs />
        </Container>
      </Box>
      <Box my="8" >
        <Container maxW={{ base: "sm", md: "6xl" }}>
          <Box py="8" display="flex" flexDirection="column" alignItems="center">
            <SectionHeader>Ready to connect?</SectionHeader>
            <Box
              boxShadow="2xl"
              borderRadius="15px"
              bg="whiteAlpha.900"
              p="6"
              mt="6"
              display="flex"
              alignItems="center"
              maxW="container.sm"
            >
              insert image as background for the top half of this card
              <Box display="flex" flexDirection="column" justifyContent="center" alignItems="center">
                <Text textAlign="center" mb="2">If you're ready to start getting to know others through language...</Text>
                <Button colorScheme="brand" onClick={() => router.push('/signup')}>Sign Up!</Button>
              </Box>
            </Box>
          </Box>
        </Container>

      </Box>
    </Box>
  )
}
